version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - APP_ID=1088069726409871450
      - BOT_TOKEN=MTA4ODA2OTcyNjQwOTg3MTQ1MA.GTHzQS.732y7wZUk4iC8mc3ljTttvmANoUu6HgHDfDUdI
      - GUILD_ID=1128200833222328364
      - R_OP=1128200833654325330
      - R_STAFF=1128200833654325330
      - TC_SENTRY=1128200834413506684
      - APP_ENV=DEVELOP
      - APP_DEBUGING=TRUE
      - DISCORD_WEBHOOK_URL=
      - DASHBOARD_URL=https://127.0.0.1:8000/fr
    volumes:
      - ./src:/home/node/app/src
      - ./node_modules.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    command: npm run start
