version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./node_modules.json:/home/node/app/nodemon.json
    container_name: discord-edt-um
    environment:
        - TZ=Europe/Paris
    command: npm run start
